apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
      hostNetwork: true
      containers:
      - name: kube-controller-manager
        image: quay.io/coreos/hyperkube:#KUBELET_VERSION#
        command:
        - ./hyperkube
        - controller-manager
        - --master=#THIS_NODE_IP#
        - --kubeconfig=#KUBECONFIG#
        - --leader-elect=true
        - --allocate-node-cidrs=true
        - --cluster-cidr=#CIDR_NETWORK#
        - --service-cluster-ip-range=10.3.0.0/21
        - --service-account-private-key-file=#ETCDCTL_KEY_FILE2#
        - --root-ca-file=#CA_FILE1#
        - --cluster-signing-key-file=#CA_FILE1#
        - --service-account-private-key-file=#ETCDCTL_KEY_FILE2#
        - --root-ca-file=#CA_FILE1#
        - --cluster-signing-cert-file=#CA_FILE1#
        livenessProbe:
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 10252  # Note: Using default port. Update if --port option is set differently.
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-host
          readOnly: true
        - mountPath: /var/log/kube-controller-manager.log
          name: logfile
          readOnly: false
        - mountPath: #KUB_SSL_DIR#"
          name: "kube-ssl"
          readOnly: true
      volumes:
      - hostPath:
          path: /usr/share/ca-certificates
        name: ssl-host
      - hostPath:
          path: /var/log/kube-controller-manager.log
        name: logfile
      - hostPath:
          path: "#KUB_SSL_DIR#"
        name: "kube-ssl"
