apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    tier: node
    k8s-app: kube-proxy
spec:
      hostNetwork: true
      containers:
      - name: kube-proxy
        image: quay.io/coreos/hyperkube:#KUBELET_VERSION#
        command:
        - ./hyperkube
        - proxy
        - --master=https://#THIS_NODE_IP#:443
        - --kubeconfig=#KUBECONFIG#
        - --logtostderr=true
        - --proxy-mode=iptables
        - --hostname-override=#THIS_NODE_IP#
        - --cluster-cidr=#CIDR_NETWORK#
        - --v=3
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - name: kube-ssl
          mountPath: #KUB_SSL_DIR#
          readOnly: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - hostPath:
          path: /usr/share/ca-certificates
        name: ssl-certs-host
      - name: kube-ssl
        hostPath:
          path: #KUB_SSL_DIR#
