--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    k8s-app: kube-proxy
    tier: node
  name: kube-proxy
  namespace: kube-system
spec: 
  containers: 
    - 
      command: 
        - ./hyperkube
        - proxy
        - "--master=https://#NODE1_IP#:443"
        - "--kubeconfig=#WORK_KUBECONFIG#"
        - "--logtostderr=true"
        - "--proxy-mode=iptables"
        - "--hostname-override=#THIS_NODE_IP#"
        - "--cluster-cidr=#CIDR_NETWORK#"
        - "--v=3"
      env: 
        - 
          name: NODE_NAME
          valueFrom: 
            fieldRef: 
              fieldPath: spec.nodeName
      image: "gcr.io/google_containers/hyperkube:#KUBELET_VERSION#"
      name: kube-proxy
      securityContext: 
        privileged: true
      volumeMounts: 
        - 
          mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        -
          mountPath: #KUB_SSL_DIR#
          name: "kube-ssl"
          readOnly: true
  hostNetwork: true
  tolerations: 
    - 
      effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
  volumes: 
    - 
      hostPath: 
        path: /usr/share/ca-certificates
      name: ssl-certs-host
    - 
      hostPath:
        path: "#KUB_SSL_DIR#"
      name: "kube-ssl"
